import { type Json, type Plan } from "./domain.ts";
export const samplePlan: Plan = {
  id: "sample-plan-a",
  title:
    "Разработка и проектирование программного обеспечения информационных систем",
  program_code: "09.03.04",
  profile: "Разработка программных систем",
  level: "Бакалавриат",
  study_form: "Очная",
  admission_year: 2026,
  institute: "Институт информационных технологий",
  source_url: "https://www.mirea.ru/upload/medialibrary/example.pdf",
  quality: "partial",
  warnings: [
    "В одной строке не определён семестр. Нагрузка указана только там, где её удалось извлечь.",
  ],
  parsed_at: "2026-09-06T09:00:00Z",
  disciplines: [
    {
      id: "math-1",
      name: "Математический анализ",
      source_code: "Б1.О.01",
      semester: 1,
      control_forms: ["Экзамен"],
      hours: 144,
      credits: 4,
    },
    {
      id: "programming-1",
      name: "Основы программирования",
      semester: 1,
      control_forms: ["Зачёт с оценкой"],
      hours: 144,
      credits: 4,
    },
    {
      id: "sport-a-2",
      subject_id: "sport-a",
      name: "Атлетическая гимнастика",
      choice_group: "Физическая культура и спорт (элективные дисциплины)",
      semester: 2,
      control_forms: ["Зачёт"],
      hours: 72,
      credits: 0,
    },
    {
      id: "sport-b-2",
      subject_id: "sport-b",
      name: "Адаптивная физическая культура",
      choice_group: "Физическая культура и спорт (элективные дисциплины)",
      semester: 2,
      control_forms: ["Зачёт"],
      hours: 72,
      credits: 0,
    },
    {
      id: "optional-2",
      name: "Дополнительные главы высшей математики",
      is_optional: true,
      semester: 2,
      control_forms: ["Зачёт"],
      hours: 36,
      credits: 1,
    },
    {
      id: "unknown",
      name: "Проектная практика",
      semester: null,
      control_forms: [],
      hours: null,
      credits: null,
    },
    {
      id: "sport-a-3",
      subject_id: "sport-a",
      name: "Атлетическая гимнастика",
      choice_group: "Физическая культура и спорт (элективные дисциплины)",
      semester: 3,
      control_forms: ["Зачёт"],
      hours: 72,
      credits: 0,
    },
    {
      id: "sport-b-3",
      subject_id: "sport-b",
      name: "Адаптивная физическая культура",
      choice_group: "Физическая культура и спорт (элективные дисциплины)",
      semester: 3,
      control_forms: ["Зачёт"],
      hours: 108,
      credits: 0,
    },
  ],
};
export const otherPlan: Plan = {
  ...samplePlan,
  id: "sample-plan-b",
  title: "Информационные системы и технологии",
  program_code: "09.03.02",
  disciplines: [
    {
      ...samplePlan.disciplines[0],
      id: "math-b",
      hours: 180,
      credits: 5,
      semester: 2,
    },
    { ...samplePlan.disciplines[1], id: "programming-b" },
    {
      id: "networks",
      name: "Компьютерные сети",
      semester: 3,
      hours: 108,
      credits: 3,
      control_forms: ["Экзамен"],
    },
  ],
};
export const sampleData: Json = {
  plan: samplePlan,
  other: otherPlan,
  preferences: {
    plan_id: samplePlan.id,
    goal: "Собрать портфолио и уверенно пройти первую практику",
  },
  records: [
    { discipline_id: "math-1", note: "Повторить интегралы" },
    { discipline_id: "sport-a-2", chosen: true },
  ],
};
export const catalogData: Json = {
  plans: [samplePlan, otherPlan],
  total: 2,
  page: 0,
  filters: {
    years: [2026, 2025],
    levels: ["Бакалавриат", "Магистратура"],
    forms: ["Очная", "Очно-заочная"],
    institutes: [samplePlan.institute],
    codes: ["09.03.04", "09.03.02"],
  },
  applied: {},
  preferences: {},
};
export const parserPlanSample: Json = {
  id: "mirea-c2b3f499fa92a04009da1ece8437",
  title: "Программная инженерия",
  program_code: "09.03.04",
  profile:
    "Разработка программных продуктов и проектирование информационных систем (2026)",
  level: "Высшее образование - бакалавриат",
  study_form: "Очная",
  admission_year: 2026,
  institute: "Институт информационных технологий",
  source_url:
    "https://www.mirea.ru/25124e70a2c729685e48660fa12b89b8/sveden/files/kek/ucheb_plan_09.03.04_RPPPIS_IIT_2026.pdf",
  source_hash:
    "01b6a2c10baee1ae88f6e8493e4ea4a62f2a83f9835cbf4f3cbd918ceb41fba3",
  parser_version: "1.2.0",
  quality: "complete",
  warnings: [],
  disciplines: [
    {
      id: "9387539892f453fe65ba46a8a08cfef9",
      name: "Информатика",
      semester: 1,
      hours: 108,
      credits: 3,
      source_code: null,
      kind: "discipline",
      control_forms: ["exam"],
      choice_group: null,
      is_optional: false,
    },
    {
      id: "eae09f29a374fddc154a690b136c6bbf",
      name: "Адаптивная физическая культура",
      semester: 2,
      hours: 108,
      credits: null,
      source_code: null,
      kind: "discipline",
      control_forms: ["credit"],
      choice_group: "Физическая культура и спорт (элективные дисциплины)",
      is_optional: true,
    },
    {
      id: "3c91e2cde5d589fd59059eca1143cdbf",
      name: "Атлетическая гимнастика",
      semester: 2,
      hours: 108,
      credits: null,
      source_code: null,
      kind: "discipline",
      control_forms: ["credit"],
      choice_group: "Физическая культура и спорт (элективные дисциплины)",
      is_optional: true,
    },
  ],
};
