import type { Json } from "./domain.ts";

export const teacherId = "22222222-2222-4222-8222-222222222222";
export const otherId = "33333333-3333-4333-8333-333333333333";
export const thirdId = "44444444-4444-4444-8444-444444444444";
const badge = (
  id: string,
  title: string,
  emoji: string,
  hint: string,
  earned: boolean,
  progress: number,
  goal: number,
): Json => ({ id, title, emoji, hint, earned, progress, goal });
export const me: Json = {
  reviews: 3,
  helpful: 4,
  texts: 2,
  points: 60,
  rank: 4,
  show_in_leaderboard: false,
  display_name: "Ниндзя #A1B2",
  level: {
    index: 2,
    name: "Наблюдатель",
    emoji: "🔎",
    current: 40,
    next: 120,
    progress: 0.25,
  },
  streak_days: 2,
  best_streak: 5,
  week_reviews: 1,
  week_goal: 2,
  group_total: 8,
  group_done: 3,
  has_group: true,
  group_name: "ИКБО-40-26",
  badges: [
    badge("first", "Первый отзыв", "🎉", "Оставьте первый отзыв", true, 1, 1),
    badge(
      "five",
      "Пять преподов",
      "✋",
      "Оцените пятерых преподавателей",
      false,
      3,
      5,
    ),
    badge(
      "fifteen",
      "Знаток кафедры",
      "🔥",
      "Пятнадцать отзывов",
      false,
      3,
      15,
    ),
    badge(
      "writer",
      "Летописец",
      "✍️",
      "Три отзыва с текстом от 60 символов",
      false,
      2,
      3,
    ),
    badge(
      "group",
      "Голос группы",
      "📣",
      "Оцените троих преподавателей своей группы",
      true,
      3,
      3,
    ),
    badge(
      "helpful",
      "Полезный",
      "💡",
      "Десять отметок «полезно» от других студентов",
      false,
      4,
      10,
    ),
    badge(
      "pioneer",
      "Первопроходец",
      "🚀",
      "Первым оцените преподавателя",
      true,
      1,
      1,
    ),
    badge(
      "waves",
      "На волне",
      "🌊",
      "Отзывы в трёх разных неделях",
      false,
      2,
      3,
    ),
    badge("top", "В топе", "🏅", "Войдите в топ-10 рецензентов", true, 1, 1),
  ],
};
export const newcomer: Json = {
  ...me,
  reviews: 0,
  helpful: 0,
  texts: 0,
  points: 0,
  rank: null,
  level: {
    index: 1,
    name: "Новичок",
    emoji: "🌱",
    current: 0,
    next: 40,
    progress: 0,
  },
  streak_days: 0,
  best_streak: 0,
  week_reviews: 0,
  group_total: 0,
  group_done: 0,
  has_group: false,
  group_name: null,
  badges: (me.badges as Json[]).map((b) => ({
    ...b,
    earned: false,
    progress: 0,
  })),
};
export const teacher: Json = {
  id: teacherId,
  name: "Соколова Анна Владимировна",
  reviews: 12,
  rating: 4.62,
  clarity: 4.8,
  loyalty: 4.3,
  usefulness: 4.75,
  score: 4.51,
  rank: 2,
  recent: 3,
  last_review_at: "2026-09-12T09:15:00Z",
  top_days: 12,
  mine: true,
  followed: false,
  my_group: true,
  disciplines: ["Математический анализ", "Линейная алгебра"],
};
export const other: Json = {
  id: otherId,
  name: "Кузнецов Дмитрий Олегович",
  reviews: 1,
  rating: 3.33,
  clarity: 3,
  loyalty: 4,
  usefulness: 3,
  score: null,
  rank: null,
  recent: 1,
  top_days: 0,
  mine: false,
  followed: true,
  my_group: true,
  disciplines: ["Программирование"],
};
export const third: Json = {
  id: thirdId,
  name: "Морозов Игорь Сергеевич",
  reviews: 0,
  rating: null,
  rank: null,
  recent: 0,
  top_days: 0,
  mine: false,
  followed: false,
  my_group: true,
  disciplines: ["Физика"],
};
export const review: Json = {
  id: "55555555-5555-4555-8555-555555555555",
  teacher: teacher.name,
  teacher_id: teacherId,
  clarity: 5,
  loyalty: 4,
  usefulness: 5,
  rating: 4.7,
  body:
    "Объясняет сложные темы простыми словами, всегда приводит примеры из практики и отвечает на вопросы после пары. На зачёте спрашивает только то, что разбирали.",
  created_at: "2026-09-12T09:15:00Z",
  author: "Тестов Т.",
  anonymous: false,
  mine: true,
  helpful: 4,
  voted: false,
};
export const otherReview: Json = {
  ...review,
  id: "66666666-6666-4666-8666-666666666666",
  clarity: 4,
  loyalty: 3,
  usefulness: 4,
  rating: 3.7,
  body: "Строгий, но справедливый. Лучше не пропускать практики.",
  author: "Аноним",
  anonymous: true,
  mine: false,
  helpful: 1,
  voted: true,
  created_at: "2026-09-10T15:00:00Z",
};
export const home: Json = {
  me,
  today: [{ ...teacher, time: "10:40:00", subject: "Математический анализ" }, {
    ...third,
    time: "12:40:00",
    subject: "Физика",
  }],
  recommend: [{ ...third, occurrences: 24, today: true }, {
    ...other,
    occurrences: 12,
    today: false,
  }],
  top: [teacher, { ...other, reviews: 4, rating: 4.4, rank: 1 }, {
    ...third,
    reviews: 2,
    rating: 4.1,
    rank: 3,
  }],
  recent: [review, otherReview],
  stats: { teachers: 119, reviews: 216, week: 9, reviewers: 139 },
};
export const teacherState: Json = {
  me,
  teacher: {
    ...teacher,
    rank_clarity: 1,
    rank_loyalty: 5,
    rank_usefulness: 2,
    rank_discussed: 3,
    best_days: 15,
    eligible: 40,
    groups: 6,
    distribution: [8, 3, 1, 0, 0],
    my_review: review,
    reviews_list: [review, otherReview],
    similar: [other, third],
  },
};
export const topState: Json = {
  me,
  board: {
    board: "overall",
    scope: "all",
    count: 3,
    items: [
      { ...teacher, rank: 1, position: 1 },
      { ...other, reviews: 4, rating: 4.4, rank: 2, position: 2 },
      { ...third, reviews: 2, rating: 4.1, rank: 3, position: 3, top_days: 1 },
    ],
  },
  students: [
    {
      rank: 1,
      name: "Тестов Т.",
      points: 140,
      reviews: 9,
      helpful: 10,
      mine: false,
      streak: 9,
    },
    {
      rank: 2,
      name: "Ниндзя #C3D4",
      points: 95,
      reviews: 7,
      helpful: 5,
      mine: false,
      streak: 0,
    },
    {
      rank: 4,
      name: "Ниндзя #A1B2",
      points: 60,
      reviews: 3,
      helpful: 4,
      mine: true,
      streak: 2,
    },
  ],
};
export const meState: Json = {
  me,
  my_reviews: [{ ...review, card: teacher }, {
    ...otherReview,
    mine: true,
    teacher: other.name,
    teacher_id: otherId,
    card: other,
  }],
  followed: [other],
};
export const recommendState: Json = {
  me,
  recommend: [{
    ...third,
    occurrences: 24,
    today: true,
    time: "12:40:00",
    subject: "Физика",
  }, { ...other, occurrences: 12, today: false }],
  reviewed: [teacher],
};
